### ISSUE TITLE
Unable to install zangy

### ISSUE THREAD

**Issue by Wiper-R** [Gelbpunkt/zangy#1]

**Comment by Gelbpunkt** [comment]
Could you please provide further information? E.g. operating system, architecture, command used for installing and whether you're building from source or not.

**Comment by Wiper-R** [comment]
Windows 10, 64 Bit, `pip install zangy`

I am using `python 3.8.6`

**Comment by Gelbpunkt** [comment]
Oh yeah. I didn't provide Windows builds yet, only Linux ones. I set up builds for Windows, can you try installing it now?

**Comment by Wiper-R** [comment]
> Oh yeah. I didn't provide Windows builds yet, only Linux ones. I set up builds for Windows, can you try installing it now?

Thanks It worked!!
